### PR TITLE
Update the NSI reference data

### PR DESCRIPTION
**Pull request by electrified**
```
-- NSI Types and subtypes
SELECT JSON_objectAGG(pa.code value json_object('description' value pa.description, 'nsiTypes' value JSON_objectAGG(c.code value c.nsiType RETURNING CLOB)RETURNING CLOB) RETURNING CLOB) AS nsi_types
FROM PROBATION_AREA pa
INNER JOIN (SELECT json_object(rnt.description value st.nsiSubTypes RETURNING CLOB) AS nsiType, rnt.CODE, RNTPA.PROBATION_AREA_ID
FROM R_NSI_TYPE rnt
INNER JOIN R_NSI_TYPE_PROBATION_AREA rntpa ON RNTPA.NSI_TYPE_ID = RNT.NSI_TYPE_ID
INNER JOIN R_RQMNT_NSI_TYPE rrnt ON rrnt.NSI_TYPE_ID = rnt.NSI_TYPE_ID
INNER JOIN R_RQMNT_TYPE_MAIN_CATEGORY rrtmc ON rrtmc.RQMNT_TYPE_MAIN_CATEGORY_ID = rrnt.RQMNT_TYPE_MAIN_CATEGORY_ID
left JOIN (
SELECT rntst.NSI_TYPE_ID, JSON_objectAGG(rsrl2.CODE_VALUE value json_object('description' value rsrl2.CODE_DESCRIPTION RETURNING CLOB) RETURNING CLOB) AS nsiSubTypes
FROM r_standard_reference_list rsrl2
INNER JOIN r_nsi_type_sub_type rntst ON rsrl2.standard_reference_list_id = rntst.nsi_sub_type_id
GROUP BY rntst.NSI_TYPE_ID
) st ON st.nsi_type_id = rnt.nsi_type_id
where rnt.EVENT_LEVEL = 1
AND rnt.SELECTABLE = 'Y'
AND rrtmc.CODE = 'F'
)
c ON c.PROBATION_AREA_ID = pa.PROBATION_AREA_ID
GROUP BY pa.code, pa.DESCRIPTION;

-- Contact types
SELECT 1, json_objectagg(rct.CODE value json_object(rct.description, 'requiresLocation' value rct.CONTACT_LOCATION_FLAG, 'nsis' value c.nsiCodes, 'outcomes' value o.outcome returning clob)returning clob) AS contact_type
FROM R_CONTACT_TYPE rct 
INNER JOIN R_CONTACT_TYPECONTACT_CATEGORY rctc ON rct.CONTACT_TYPE_ID = rctc.CONTACT_TYPE_ID
INNER JOIN R_STANDARD_REFERENCE_LIST rsrl ON RCTC.STANDARD_REFERENCE_LIST_ID = rsrl.STANDARD_REFERENCE_LIST_ID
LEFT JOIN (SELECT rctnt.CONTACT_TYPE_ID, json_arrayagg(rnt.CODE) AS nsiCodes
			FROM R_NSI_TYPE rnt 
			INNER JOIN R_RQMNT_NSI_TYPE rrnt ON rrnt.NSI_TYPE_ID = rnt.NSI_TYPE_ID 
			INNER JOIN R_RQMNT_TYPE_MAIN_CATEGORY rrtmc ON rrtmc.RQMNT_TYPE_MAIN_CATEGORY_ID = rrnt.RQMNT_TYPE_MAIN_CATEGORY_ID
			INNER JOIN R_CONTACT_TYPE_NSI_TYPE rctnt ON rctnt.NSI_TYPE_ID = rnt.NSI_TYPE_ID
			WHERE rnt.NSI_TYPE_ID IN (SELECT NSI_TYPE_ID FROM R_NSI_TYPE_PROBATION_AREA rntpa
							INNER JOIN PROBATION_AREA pa ON PA.PROBATION_AREA_ID = rntpa.PROBATION_AREA_ID)
			AND rrtmc.CODE = 'F'
			AND rnt.SELECTABLE = 'Y'
			GROUP BY rctnt.CONTACT_TYPE_ID ) c ON c.CONTACT_TYPE_ID = rct.CONTACT_TYPE_ID
LEFT JOIN (SELECT rcto.CONTACT_TYPE_ID, json_arrayagg(rcot.CODE) AS outcome FROM R_CONTACT_TYPE_OUTCOME rcto
INNER JOIN R_CONTACT_OUTCOME_TYPE rcot ON rcot.CONTACT_OUTCOME_TYPE_ID = rcto.CONTACT_OUTCOME_TYPE_ID
WHERE rcot.SELECTABLE = 'Y'
GROUP BY rcto.CONTACT_TYPE_ID) o ON o.CONTACT_TYPE_ID = rct.CONTACT_TYPE_ID 
WHERE rsrl.CODE_VALUE = 'AL' AND rct.SELECTABLE = 'Y' AND FUTURE_SCHEDULED_CONTACTS_FLAG = 'Y' AND ATTENDANCE_CONTACT = 'Y' AND rct.CJA_ORDERS = 'Y'
GROUP BY 1;
```

```
cat nsi2.json | jq --sort-keys 'walk(if type == "array" then sort else . end)' > nsi.json
```

### CODE REVIEW

**Comment by fofr** [comment]
This breaks the arrange appointment RAR category flow from what I can see:

Screenshot 2021-09-08 at 14 35 10

**Comment by fofr** [comment]
We have this mapping, which I don't think will work anymore as I can't find NPS001 etc in the new list:

```'NPS001': 'Accommodation',
      'NPS002': 'Attitudes, thinking and behaviour',
      'NPS003': 'Children and families',
      'NPS004': 'Drugs and alcohol',
      'NPS005': 'Education, training and employment',
      'NPS006': 'Finance, benefits and debt',
      'NPS007': 'Mental health',
      'NPS008': 'Physical health',
      'NPS009': 'Restorative justice',
      'NPS010': 'Specific interventions for women',
      'NPS011': 'Other'```

**Comment by benilovj** [comment]
@electrified I think the reason why the prototype code is breaking is a subtle difference in how the `nsi.json` file is structured...

image

Unless I'm reading it wrong, the `nsiTypes` Object no longer has `description` and `nsiSubtypes` keys?

**Comment by electrified** [comment]
@benilovj This is now fixed. Forgot that the SQL doesn't return it in the right structure!

**Comment by fofr** [comment]
We aren't going to get to this now.

**Pull request closed without merging**
