### PR TITLE
Add an 'other communications' page

### PR DESCRIPTION
**Pull request by benilovj**
## Email to a 3rd party

image

## Text message from the service user

image

### CODE REVIEW

**Comment by benilovj** [comment]
@kelliedesigner @duffylouise I've taken it from the Google prototype, but is it appropriate that the label for communication contents is "Notes", rather than "Contents" or "Body" or similar?

**Comment by duffylouise** [comment]
Good spot. I think it should say "Details" there as "Notes" is used for for PPs to add additional info for things like appointments.

**Comment by benilovj** [comment]
> Good spot. I think it should say "Details" there as "Notes" is used for for PPs to add additional info for things like appointments.

Thanks – have amended to "Details".

**Review by kelliedesigner — APPROVED** [review]
LGTM

**Pull request merged**
